[database_group]
pg-primary anisble_host=192.168.10.20 ansible_user=gottlieb
pg-replica anisble_host=192.168.10.21 ansible_user=gottlieb

[monitoring_group]
monitoring anisble_host=192.168.10.60 ansible_user=gottlieb
